export const GET_FRESH_TOKEN_REQUEST = 'GET_FRESH_TOKEN_REQUEST';
export const GET_FRESH_TOKEN_SUCCESS = 'GET_FRESH_TOKEN_SUCCESS';
export const GET_FRESH_TOKEN_FAILURE = 'GET_FRESH_TOKEN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
